In [1]:
import torch

### **Build the data**

In [2]:
torch.manual_seed(1)

# Define max and min int
max_int = 1000
min_int = -1000

# Define number of examples
num_examples = 100000
nums = torch.randint(min_int, max_int, (num_examples,2))
nums

tensor([[ 845, -861],
        [-876,  368],
        [ 263, -687],
        ...,
        [-903,  -74],
        [-510,  652],
        [ 588,  583]])

In [3]:
# Add targets
# Compute the sum of each row (along dimension 1)
sums = nums.sum(dim=1, keepdim=True)

# Concatenate the sums as a new column
data = torch.cat((nums, sums), dim=1)
data

tensor([[ 845, -861,  -16],
        [-876,  368, -508],
        [ 263, -687, -424],
        ...,
        [-903,  -74, -977],
        [-510,  652,  142],
        [ 588,  583, 1171]])

In [4]:
#--------------------------------------------------------------
# Build the Splits
#--------------------------------------------------------------
# Set split proportions
train_pct = 0.9
val_pct = 0.1
test_pct = 0.0      # We wont define a test set for now

# Calculate split indexes
n1 = int(train_pct * data.size()[0])
n2 = int((train_pct + val_pct) * data.size()[0])

# Create splits
train_data = data[:n1]
val_data = data[n1:n2]
test_data = data[n2:]

In [5]:
batch_size = 4

In [6]:
def get_batch(split):
    # Define data split to pick from
    if split == 'train':
        data = train_data
    elif split == 'val':
        data = val_data
    elif split == 'test':
        data = test_data
    else:
        raise ValueError(f"Invalid split value: '{split}'. Expected one of: 'train', 'val', 'test'.")
    
    # Generate #batch_size random indexes
    ix = torch.randint(data.size()[0], (batch_size,))
     
    # Gather inputs (x) and targets (y)
    x = torch.stack([data[i, :2] for i in ix])
    y = torch.stack([data[i, -1] for i in ix])
    return x, y


In [7]:
x, y = get_batch('train')
print(x)
print(y)

tensor([[-664,  342],
        [ 157, -333],
        [ 766,  452],
        [ 753,  303]])
tensor([-322, -176, 1218, 1056])


In [40]:
-694+809

115